# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cabe No Carrinho' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Cabe No Carrinho
  pod 'SVProgressHUD'
  pod 'UIFloatLabelTextField'
end
